title: ens-T-era
email: ensterasolutions@gmail.com
description: >-
  Tools, apps, and dashboards to simplify your business processes.
baseurl: "" # Leave this empty for GitHub Pages root
url: "https://enstera.github.io"

remote_theme: mmistakes/minimal-mistakes

logo: /assets/images/logo.png

author:
  name: ens-T-era
  avatar: /assets/images/logo.png

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Navigation bar
header_pages:
  - index.md
  - tools.md
  - contact.md
  - about.md
