title: ens-T-era
email: ensterasolutions@gmail.com
description: >-
  Tools, apps, and dashboards to simplify your business processes.
baseurl: "" # leave empty if deploying at root
url: "https://enstera.github.io"

theme: minimal-mistakes-jekyll

logo: /assets/images/logo.png

# Social Links (optional)
author:
  name   : ens-T-era
  avatar : /assets/images/logo.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Navigation bar
header_pages:
  - index.md
  - tools.md
  - contact.md
  - about.md
